// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/wandofi-hero/RedFrame.tsx": () => import("../components/mockups/wandofi-hero/RedFrame.tsx"),
  "./components/mockups/wandofi-redlight/Horizon.tsx": () => import("../components/mockups/wandofi-redlight/Horizon.tsx"),
  "./components/mockups/wandofi-redlight/Spotlight.tsx": () => import("../components/mockups/wandofi-redlight/Spotlight.tsx"),
  "./components/mockups/wandofi-redlight/Threshold.tsx": () => import("../components/mockups/wandofi-redlight/Threshold.tsx"),
  "./components/mockups/wandofi-usability/Accessible.tsx": () => import("../components/mockups/wandofi-usability/Accessible.tsx"),
  "./components/mockups/wandofi-usability/Affordance.tsx": () => import("../components/mockups/wandofi-usability/Affordance.tsx"),
  "./components/mockups/wandofi-usability/Hierarchy.tsx": () => import("../components/mockups/wandofi-usability/Hierarchy.tsx")
};
