// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/wandofi-hero/RedFrame.tsx": () => import("../components/mockups/wandofi-hero/RedFrame.tsx")
};
